version: '3'
services: 
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes: 
      - /app/node_modules
      - ./app
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
    stdin_open: true